name: network_caller_http
description: HTTP implementation of network_caller using package:http. Handles tokens, retry, logging, cancellation — zero boilerplate.
version: 1.0.0
homepage: https://github.com/Md-LatifurRatul/custom_network_caller
repository: https://github.com/Md-LatifurRatul/custom_network_caller/tree/main/packages/network_caller_http
topics:
  - networking
  - http
  - api
  - rest
  - http-client

resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  network_caller_core:
    path: ../network_caller_core
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.0
